### ISSUE TITLE
Actuator Specification - Parsing issue

### ISSUE THREAD

**Issue by pankeshpatel** [pankeshlinux/IoTSuite#3]
When I specify  
       Heater  // Interchanging the sequence of  Parameterized and no parameterized action commands
          action SetTemp(setTemp:TempStruct);  
          action Off();

The generated code produces -  Off(TempStruct arg). 

But I 

```
Heater 
     action Off();
      action SetTemp(setTemp:TempStruct);   
```

Everything works correctly

**Comment by KaranbeerKaur** [comment]
Hi Team,

I after successfully executing "compile-vocab-spec " and "compile-arch-spec " commands. I am executing "compile-deploy-spec " command. But it is giving below error 
   "Directory does not exist.    /path/IoT/Template/DeviceDrivers/EndUserApp"

seems vocb and arch commands are not generating required folders for deploy command. 
Kindly help or let know me know if I am missing any step.

Thanks

**Comment by KaranbeerKaur** [comment]
Hi Team,

In "GlobalVariable." class variable is declared like this "public static String frameworkRootDir;" and is used in 4 methods,But it is never initialized in code. Can you please mention what value needs to be initialize for this variable.

Thanks
